DROP DATABASE IF EXISTS WOMEN_SOCCER;

CREATE DATABASE WOMEN_SOCCER;

USE WOMEN_SOCCER;

CREATE TABLE clubs (
  club_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  club_name VARCHAR(30)
);

INSERT INTO clubs (club_name) VALUES
('Avaí/Kindermann'),
('Bahia'),
('Botafogo'),
('Corinthians'),
('Cruzeiro'),
('Ferroviária'),
('Flamengo'),
('Grêmio'),
('Internacional'),
('Minas Brasília'),
('Napoli-SC'),
('Palmeiras'),
('Real Brasília'),
('Santos'),
('São José-SP'),
('São Paulo');

CREATE TABLE players (
  player_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  player_name VARCHAR(30) NOT NULL,
  player_position VARCHAR(30) NOT NULL,
  club_id INT,
  FOREIGN KEY (club_id) REFERENCES clubs(club_id)
);

INSERT INTO players (player_name, player_position, club_id) VALUES
('Letícia Busatto','GOLEIRA',1),('Bárbara Micheline','GOLEIRA',1),('Camila Silva','ZAGUEIRA',1),
('Simeia','ZAGUEIRA',1),('Carla','ZAGUEIRA',1),('Tuani','ZAGUEIRA',1),
('Geovana da Silva','LATERAL',1),('Fran','LATERAL',1),('Carol','LATERAL',1),
('Bárbara Santos','LATERAL',1),('Geovana Alves','MEIA',1),('Vilma','MEIA',1),
('Gaby','MEIA',1),('Paty','MEIA',1),('Patricia Derrico','MEIA',1),('Karina','MEIA',1),
('Zoio','MEIA',1),('Sthephanie','MEIA',1),('Larissa','ATACANTE',1),('Raiza','ATACANTE',1),
('Catyellen','ATACANTE',1),('Lelê','ATACANTE',1),('Anna Bia','GOLEIRA',2),
('Dymenor','LATERAL',2),('Luana','LATERAL',2),('Nine','LATERAL',2),('Tayane','LATERAL',2),
('Aila','ZAGUEIRA',2),('Nainara','ZAGUEIRA',2),('Eddie','MEIA',2),('Esquerdinha','MEIA',2),
('Jordana','MEIA',2),('Kaylane','MEIA',2),('Milene Bispo','MEIA',2),('Vi','MEIA',2),
('Ellen Santana','ATACANTE',2),('Verena','ATACANTE',2),('Lívia Leal','GOLEIRA',3),
('Rubi','GOLEIRA',3),('Ingrid Sabino','GOLEIRA',3),('Mayara','GOLEIRA',3),
('Carol Carioca','DEFENSOR',3),('Mylena Carioca','DEFENSOR',3),('Bruh','DEFENSOR',3),
('Chaiane','DEFENSOR',3),('Sandrinha','DEFENSOR',3),('Karen Bender','DEFENSOR',3),
('Thamires Ferreira','DEFENSOR',3),('Thaisa','DEFENSOR',3),('Amanda','DEFENSOR',3),
('Laura','DEFENSOR',3),('Vivian','MEIA',3),('Maca López','MEIA',3),('Laura Spenazzatto','MEIA',3),
('Pepê','MEIA',3),('Ingrid Micaele','MEIA',3),('Driely','MEIA',3),('Gaby Louvain','MEIA',3),
('Camila Oliveira','MEIA',3),('Cris','ATACANTE',3),('Juliana','ATACANTE',3),('Karol LIns','ATACANTE',3),
('Emily','ATACANTE',3),('Kamila Sotero','ATACANTE',3),('Kélen Bender','ATACANTE',3),
('Isabella Rangel','ATACANTE',3),('Kailane','ATACANTE',3),('Isa Cruz','GOLEIRA',4),
('Kemelli','GOLEIRA',4),('Natascha','GOLEIRA',4),('Paty','GOLEIRA',4),('Tainá','GOLEIRA',4),
('Tarciane','ZAGUEIRA',4),('Campiolo','ZAGUEIRA',4),('Poliana','ZAGUEIRA',4),
('Erika','ZAGUEIRA',4),('Pardal','ZAGUEIRA',4),('Katiuscia','LATERAL',4),('Tamires','LATERAL',4),
('Yasmim','LATERAL',4),('Andressinha','MEIA',4),('Diany','MEIA',4),('Gabi Zanotti','MEIA',4),
('Ingryd','MEIA',4),('Juliete','MEIA',4),('Victoria','MEIA',4),('Grazi','MEIA',4),('Bianca Gomes','ATACANTE',4),
('Gabi Portilho','ATACANTE',4),('Jheniffer','ATACANTE',4),('Miriã','ATACANTE',4),('Adriana','ATACANTE',4),
('Cacau','ATACANTE',4),('Taty SIlva','GOLEIRA',5),('Mary','GOLEIRA',5),('Dafiny','GOLEIRA',5),('Thalita','DEFENSOR',5),
('Mariana Pires','DEFENSOR',5),('Eskerdinha','DEFENSOR',5),('Mayara','DEFENSOR',5),('Janaína','DEFENSOR',5),
('Jessica Romero','DEFENSOR',5),('Rebeca','DEFENSOR',5),('Mayara Vaz','MEIA',5),('Duda','MEIA',5),
('Lucero Robayo','MEIA',5),('Camila Ambrózio','MEIA',5),('Carol Shimo','MEIA',5),('Isabela Cepelinha','MEIA',5),
('Vanessa','ATACANTE',5),('Pâmela','ATACANTE',5),('Marília','ATACANTE',5),('Thamirys','ATACANTE',5),
('Carol','ATACANTE',5),('Leilane','GOLEIRA',6),('Luciana','GOLEIRA',6),('Lucilene','GOLEIRA',6),
('Yanne','GOLEIRA',6),('Laisla','GOLEIRA',6),('Raquel Maisa','DEFENSOR',6),('Nicoly','DEFENSOR',6),
('Ana Alice','DEFENSOR',6),('Luana Sartório','DEFENSOR',6),('Daiane Rodrigues','DEFENSOR',6),
('Barrinha','DEFENSOR',6),('Lurdinha','DEFENSOR',6),('Yasmin Cosmann','DEFENSOR',6),
('Géssica','DEFENSOR',6),('Anny','DEFENSOR',6),('Letícia Seabra','DEFENSOR',6),('Duda','DEFENSOR',6),
('Catarina','MEIA',6),('Tamires','MEIA',6),('Aninha Hansen','MEIA',6),('Graciela Martínez','MEIA',6),
('Monaliza Belém','MEIA',6),('Patrícia Sochor','MEIA',6),('Carol Tavarez','MEIA',6),('Leide','MEIA',6),
('Thaynara Oliveira','MEIA',6),('Amanda Brunner','MEIA',6),('Suzane Pires','MEIA',6),('Maísa','MEIA',6),
('Isabelle Garcia','MEIA',6),('Aline','MEIA',6),('Duda Batista','MEIA',6),('Bruna','ATACANTE',6),
('Laura Pigatin','ATACANTE',6),('Raissa Silva','ATACANTE',6),('Aline Milene','ATACANTE',6),
('Sâmila Pryscila','ATACANTE',6),('Ludmila Barbosa','ATACANTE',6),('Raquel Fernandes','ATACANTE',6),
('Rafa Mineira','ATACANTE',6),('Gabi Croco','GOLEIRA',7),('Kaká','GOLEIRA',7),('Tainá','GOLEIRA',7),
('Yasmin','GOLEIRA',7),('Cida','DEFENSOR',7),('Renata DIniz','DEFENSOR',7),('Stella','DEFENSOR',7),
('Débora Sorriso','LATERAL',7),('Raquel','LATERAL',7),('Jissele','LATERAL',7),('Carol Ladaga','LATERAL',7),
('Ana Portugal','LATERAL',7),('Bruna Rosa','MEIA',7),('Carol Matos','MEIA',7),('Kaylane','MEIA',7),
('Larissa Baiana','MEIA',7),('Lorraynne','MEIA',7),('Naely','MEIA',7),('Scarlett','MEIA',7),
('Ana Carla','MEIA',7),('Aryane','MEIA',7),('Carlinha','MEIA',7),('Dedê','MEIA',7),('Jayanne','MEIA',7),
('Samhia','MEIA',7),('Andressa Lodi','ATACANTE',7),('Dani Ortolan','ATACANTE',7),('Flávia','ATACANTE',7),
('Rafa Barros','ATACANTE',7),('Rhaizza','ATACANTE',7),('Thalita','ATACANTE',7),('Tuane','ATACANTE',7),
('Lorena','GOLEIRA',8),('Raíssa','GOLEIRA',8),('Sinara','LATERAL',8),('Vitória Kaíssa','LATERAL',8),
('Gisseli','LATERAL',8),('Isa','LATERAL',8),('Laís','LATERAL',8),('Andréia Rosa','DEFENSOR',8),
('Lorena Gonzalez','DEFENSOR',8),('Nataliê','DEFENSOR',8),('Patricia Maldaner','DEFENSOR',8),
('Andressa Pereira','DEFENSOR',8),('Kika Brandinho','MEIA',8),('Maglia','MEIA',8),
('Mariza','MEIA',8),('Mayara Farias','MEIA',8),('Pri Back','MEIA',8),('Rafa Levis','MEIA',8),('Tchula','MEIA',8),
('Jé Alvez','MEIA',8),('Jane Tavares','MEIA',8),('Maiara Lisboa','ATACANTE',8),('Nathane Fabem','ATACANTE',8),
('Eudimilla','ATACANTE',8),('Gabizinha','ATACANTE',8),('Lais Estevam','ATACANTE',8),('Vivi' ,'GOLEIRA',9),('Mayara Nabosne','GOLEIRA',9),
('Sabrina','GOLEIRA',9),('Gabi Barbieri','GOLEIRA',9),('Leidi','DEFENSOR',9),('Bruna Benites','DEFENSOR',9),('Sorriso','DEFENSOR',9),
('Belinha','DEFENSOR',9),('Ariely','DEFENSOR',9),('Ariane Cabrera','DEFENSOR',9),('Isa Haas','DEFENSOR',9),
('Kewllen','DEFENSOR',9),('Maiara Niehues','DEFENSOR',9),('Duda Flores','DEFENSOR',9),('Liriel','DEFENSOR',9),
('Gilmara','MEIA',9),('Ju Ferreira','MEIA',9),('Djeni','MEIA',9),('Mariana Neiva','MEIA',9),
('Rafa Travalão','MEIA',9),('Ximena Velazco','MEIA',9),('Bárbara','MEIA',9),('Thessa','MEIA',9),
('Vick','MEIA',9),('Kamila Konrad','MEIA',9),('Mileninha','MEIA',9),('Milene','ATACANTE',9),('Fabiana Simões','ATACANTE',9),
('Wendy Carballo','ATACANTE',9),('Kamile','ATACANTE',9),('Luana Gabias','ATACANTE',9),('Priscila','ATACANTE',9),
('Bianca Gomes','ATACANTE',9),('Tâmara','ATACANTE',9),('Shashá','ATACANTE',9),('Tainá Maranhão','ATACANTE',9),
('Janny','GOLEIRA',10),('Karen','GOLEIRA',10),('Bia' ,'DEFENSOR',10),('Dih','DEFENSOR',10),
('Kaká','DEFENSOR',10),('Luy','DEFENSOR',10),('Lia','DEFENSOR',10),('Jéh','LATERAL',10),
('Kati','LATERAL',10),('Madu','LATERAL',10),('Suzana','LATERAL',10),('Bruna','MEIA',10),
('Gabi Arcanjo','MEIA',10),('Isa','MEIA',10),('Karla','MEIA',10),('Monse','MEIA',10),('Giulia','MEIA',10),
('Manu','MEIA',10),('Lay','MEIA',10),('Farinon','ATACANTE',10),('Nenê','ATACANTE',10),('Pelé','ATACANTE',10),
('Prince','ATACANTE',10),('Robinha','ATACANTE',10),('Stef','ATACANTE',10),('Dalva','GOLEIRA',11),
('Fernanda Delazere','GOLEIRA',11),('Gaby Souza','GOLEIRA',11),('Miriam','DEFENSOR',11),('Thaíni','DEFENSOR',11),('Júlia Cipriani','DEFENSOR',11),
('Thays','DEFENSOR',11),('Yaki Vecca','DEFENSOR',11),('Maria Eduarda','MEIA',11),('Luana Rodrigues','MEIA',11),('Juliana Santos','MEIA',11),
('Jaine Lemke','MEIA',11),('Martinha','MEIA',11),('Aninha','ATACANTE',11),('Awanny','GOLEIRA',12),('Jully','GOLEIRA',12),
('Taty Amaro','GOLEIRA',12),('Agustina','DEFENSOR',12),('Carolzinha','DEFENSOR',12),('Karol Arcanjo','DEFENSOR',12),('Tainara','DEFENSOR',12),
('Thais','DEFENSOR',12),('Bruna Calderan','LATERAL',12),('Evelin','LATERAL',12),('Julinha','LATERAL',12),('Manuela','LATERAL',12),
('Ana Clara','MEIA',12),('Ary Borges','MEIA',12),('Camilinha','MEIA',12),('Dóroty','MEIA',12),('Duda Santos','MEIA',12),
('Julia Bianchi','MEIA',12),('Juliana','MEIA',12),('Katrine','MEIA',12),('Rafa Andrade','MEIA',12),('Thayná','MEIA',12),
('Carol Baiana','ATACANTE',12),('Chú','ATACANTE',12),('Dandara','ATACANTE',12),('Giovana','ATACANTE',12),('Mariana Alves','ATACANTE',12),
('Ottilia','ATACANTE',12),('Thais Amorim','GOLEIRA',13), ('Jeane','GOLEIRA',13), ('Stefane','GOLEIRA',13),
('Flavinha','GOLEIRA',13), ('Roberta Schroeder','DEFENSOR',13), ('Rafa Soares','DEFENSOR',13),
('Belão','DEFENSOR',13), ('Lana','DEFENSOR',13), ('Jamille','DEFENSOR',13),
('Raquel','DEFENSOR',13), ('Bruna Natieli','DEFENSOR',13), ('Natasha Rosas','DEFENSOR',13),
('Petra Cabrera','DEFENSOR',13), ('Letícia Leme','MEIO',13), ('Taci Sam','MEIO',13),
('Geovana Alves','MEIO',13), ('Rafa Ancheta','MEIO',13), ('Janete','MEIO',13),
('Eliane','MEIO',13), ('Sabrina','MEIO',13), ('Maiara Santos','MEIO',13),
('Camila Pini','MEIO',13), ('Margareth','MEIO',13), ('Thaizinha','MEIO',13),
('Amanda Ribeiro','MEIO',13), ('Marcela','ATACANTE',13), ('Pity','ATACANTE',13),
('Tábatha','ATACANTE',13), ('Pity','ATACANTE',13), ('Daniele','ATACANTE',13),
('Camila Gomes','GOLEIRA',14), ('Dida','GOLEIRA',14), ('Michele','GOLEIRA',14),
('Sassá','DEFENSOR',14), ('Day Silva','DEFENSOR',14), ('Tayla','DEFENSOR',14),
('Camila','DEFENSOR',14), ('Bruninha','LATERAL',14), ('Fe Palermo','LATERAL',14),
('Júlia Daltoé','MEIA',14), ('Gi Fernandes','MEIA',14), ('Nicole Marussi','MEIA',14),
('Luana','MEIA',14), ('Laura Valverde','MEIA',14), ('Bia Menezes','MEIA',14),
('Rita Bove','MEIA',14), ('Alanna','MEIA',14), ('Brena','MEIA',14),
('Erikinha','MEIA',14), ('Byanca Brasil','ATACANTE',14), ('Analuyza','ATACANTE',14),
('Thaisinha','ATACANTE',14), ('Cristiane','ATACANTE',14), ('Amanda Gutierrez','ATACANTE',14),
('Maria Dias','ATACANTE',14), ('Karen','ATACANTE',14), ('Ketlen','ATACANTE',14),
('Zani','GOLEIRA',15), ('Jéssica Ferreira','GOLEIRA',15), ('Renata May','GOLEIRA',15),
('Suelem','DEFENSOR',15), ('Gabi Batista','DEFENSOR',15), ('Verónica Riveros','DEFENSOR',15),
('Karen','DEFENSOR',15), ('Juju','DEFENSOR',15), ('Bruna Amarante','DEFENSOR',15),
('Letícia Fagundes','DEFENSOR',15), ('Camila Costa','DEFENSOR',15), ('Vitória Calhau','DEFENSOR',15),
('Evellyn Marques','DEFENSOR',15), ('Larissa Vasconcelos','MEIA',15), ('Mariane','MEIA',15),
('Sara Piveta','MEIA',15), ('Jaielly','MEIA',15), ('Adyla','MEIA',15),
('Bárbara Santos','MEIA',15), ('Nati Maia','MEIA',15), ('Rafa Marques','MEIA',15),
('Baiana','MEIA',15), ('Ionara','MEIA',15), ('Thaymara Araújo','MEIA',15),
('Verônica Marques','MEIA',15), ('Thainá','ATACANTE',15), ('Naiane','ATACANTE',15),
('Verena','ATACANTE',15), ('Julina Oliveira','ATACANTE',15), ('Giovânia','ATACANTE',15),
('Bea','ATACANTE',15),
('Thaís Helena','GOLEIRA',16), ('Carlinha','GOLEIRA',16), ('Marcelle','GOLEIRA',16),
('Giovana','DEFENSOR',16), ('Thaís Regina','DEFENSOR',16), ('Letícia Alves','DEFENSOR',16),
('Natane','DEFENSOR',16), ('Dani Silva','DEFENSOR',16), ('Gislaine','DEFENSOR',16),
('Ana Clara','DEFENSOR',16), ('Lauren','DEFENSOR',16), ('Nath Pitbull','MEIA',16),
('Mirim Cris','MEIA',16), ('Formiga','MEIA',16), ('Duda','MEIA',16),
('Micaelly','MEIA',16), ('Naná','MEIA',16), ('Maressa','MEIA',16),
('Vitória Yaya','MEIA',16), ('Carol','MEIA',16), ('Carla Nunes','ATACANTE',16),
('Mônica Bitencourt','ATACANTE',16), ('Carol Nogueira','ATACANTE',16), ('Gláucia','ATACANTE',16),
('Lary Santos','ATACANTE',16), ('Gica','ATACANTE',16), ('Mylla','ATACANTE',16),
('Jaqueline Ribeiro','ATACANTE',16), ('Isabelle','ATACANTE',16), ('Giovaninha','ATACANTE',16);

CREATE TABLE matches (
  match_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  club_id_1 INT NOT NULL,
  club_id_2 INT NOT NULL,
  match_round INT NOT NULL,
  FOREIGN KEY (club_id_1) REFERENCES clubs(club_id),
  FOREIGN KEY (club_id_2) REFERENCES clubs(club_id)
);

INSERT INTO matches (club_id_1, club_id_2, match_round) VALUES
(16,8,1), (9,14,1), (4,11,1),
(3,2,1), (7,10,1), (5,13,1),
(12,6,1), (15,1,1), (1,12,2),
(2,9,2), (13,3,2), (6,4,2),
(8,5,2), (14,16,2), (10,15,2),
(11,7,2), (1,8,3), (12,5,3),
(11,2,3), (7,9,3), (6,13,3),
(4,3,3), (15,16,3), (10,14,3),
(2,6,4), (13,1,4), (5,15,4),
(16,7,4), (9,4,4), (3,12,4),
(8,10,4), (14,11,4), (1,16,5),
(9,6,5), (10,5,5), (2,7,5),
(15,13,5), (14,4,5), (3,11,5),
(12,8,5);

CREATE TABLE goals (  
  player_id INT NOT NULL,
  match_id INT NOT NULL,
  goal_way CHAR NOT NULL,
  FOREIGN KEY (player_id) REFERENCES players(player_id),  
  FOREIGN KEY (match_id) REFERENCES matches(match_id)
);	

INSERT INTO goals (player_id, match_id, goal_way) VALUES
  (424,1,"F"),(211,1,"F"),
  (242,2,"F"),(367,2,"C"),
  (63,4,"F"),(185,5,"F"),
  (272,5,"F"),(110,6,"F"),
  (312,7,"F"),(147,7,"F"),
  (19,9,"C"),(312,9,"F"),
  (242,10,"F"),(341,11,"F"),
  (63,11,"F"),(211,13,"F"),
  (367,14,"F"),(424,14,"C"),
  (403,15,"F"),(19,17,"F"),
  (211,17,"F"),(312,18,"F"),
  (110,18,"C"),(287,19,"F"),
  (37,19,"F"),(242,20,"F"),
  (147,21,"F"),(341,21,"F"),
  (63,22,"F"),(67,22,"F"),
  (403,23,"F"),(424,23,"F"),
  (272,24,"F"),(367,24,"F"),
  (147,25,"F"),(341,26,"F"),
  (110,27,"F"),(403,27,"F"),
  (424,28,"F"),(63,30,"F"),
  (312,30,"F"),(211,31,"C"),
  (367,32,"F"),(287,32,"F"),
  (19,33,"F"),(424,33,"F"),
  (242,34,"F"),(147,34,"F"),
  (272,35,"F"),(110,35,"F"),
  (185,36,"F"),(341,37,"F"),
  (367,38,"F"),(63,39,"F"),
  (67,39,"F"),(312,40,"F"),
  (211,40,"C");
