module.exports = {
  up: async (queryInterface) => {
    /**
     * Add seed commands here.
     *
     * Example:
     */
    await queryInterface.bulkInsert(
      'players',
      [
        {
          player_name: 'Letícia Busatto',
          position: 'GOLEIRA',
          club_id: 1,
          goals: 0,
        },
        {
          player_name: 'Camila Silva',
          position: 'ZAGUEIRA',
          club_id: 1,
          goals: 0,
        },
        {
          player_name: 'Simeia',
          position: 'ZAGUEIRA',
          club_id: 1,
          goals: 0,
        },
        {
          player_name: 'Tuani',
          position: 'ZAGUEIRA',
          club_id: 1,
          goals: 0,
        },
        {
          player_name: 'Geovana da Silva',
          position: 'LATERAL',
          club_id: 1,
          goals: 0,
        },
        {
          player_name: 'Fran',
          position: 'LATERAL',
          club_id: 1,
          goals: 0,
        },
        {
          player_name: 'Geovana Alves',
          position: 'MEIA',
          club_id: 1,
          goals: 1,
        },
        {
          player_name: 'Vilma',
          position: 'MEIA',
          club_id: 1,
          goals: 0,
        },
        {
          player_name: 'Gaby',
          position: 'MEIA',
          club_id: 1,
          goals: 0,
        },
        {
          player_name: 'Larissa',
          position: 'ATACANTE',
          club_id: 1,
          goals: 0,
        },
        {
          player_name: 'Raiza',
          position: 'ATACANTE',
          club_id: 1,
          goals: 3,
        },
        {
          player_name: 'Anna Bia',
          position: 'GOLEIRA',
          club_id: 2,
          goals: 0,
        },
        {
          player_name: 'Nine',
          position: 'LATERAL',
          club_id: 2,
          goals: 0,
        },
        {
          player_name: 'Tayane',
          position: 'LATERAL',
          club_id: 2,
          goals: 0,
        },
        {
          player_name: 'Aila',
          position: 'ZAGUEIRA',
          club_id: 2,
          goals: 1,
        },
        {
          player_name: 'Nainara',
          position: 'ZAGUEIRA',
          club_id: 2,
          goals: 0,
        },
        {
          player_name: 'Eddie',
          position: 'MEIA',
          club_id: 2,
          goals: 0,
        },
        {
          player_name: 'Esquerdinha',
          position: 'MEIA',
          club_id: 2,
          goals: 0,
        },
        {
          player_name: 'Milene Bispo',
          position: 'MEIA',
          club_id: 2,
          goals: 0,
        },
        {
          player_name: 'Vi',
          position: 'MEIA',
          club_id: 2,
          goals: 0,
        },
        {
          player_name: 'Ellen Santana',
          position: 'ATACANTE',
          club_id: 2,
          goals: 0,
        },
        {
          player_name: 'Verena',
          position: 'ATACANTE',
          club_id: 2,
          goals: 2,
        },
        {
          player_name: 'Lívia Leal',
          position: 'GOLEIRA',
          club_id: 3,
          goals: 0,
        },
        {
          player_name: 'Carol Carioca',
          position: 'DEFENSOR',
          club_id: 3,
          goals: 0,
        },
        {
          player_name: 'Mylena Carioca',
          position: 'DEFENSOR',
          club_id: 3,
          goals: 0,
        },
        {
          player_name: 'Vivian',
          position: 'MEIA',
          club_id: 3,
          goals: 0,
        },
        {
          player_name: 'Maca López',
          position: 'MEIA',
          club_id: 3,
          goals: 0,
        },
        {
          player_name: 'Laura Spenazzatto',
          position: 'MEIA',
          club_id: 3,
          goals: 0,
        },
        {
          player_name: 'Pepê',
          position: 'MEIA',
          club_id: 3,
          goals: 0,
        },
        {
          player_name: 'Cris',
          position: 'ATACANTE',
          club_id: 3,
          goals: 0,
        },
        {
          player_name: 'Karol LIns',
          position: 'ATACANTE',
          club_id: 3,
          goals: 0,
        },
        {
          player_name: 'Emily',
          position: 'ATACANTE',
          club_id: 3,
          goals: 1,
        },
        {
          player_name: 'Kamila Sotero',
          position: 'ATACANTE',
          club_id: 3,
          goals: 2,
        },
        {
          player_name: 'Isa Cruz',
          position: 'GOLEIRA',
          club_id: 4,
          goals: 0,
        },
        {
          player_name: 'Tarciane',
          position: 'ZAGUEIRA',
          club_id: 4,
          goals: 1,
        },
        {
          player_name: 'Campiolo',
          position: 'ZAGUEIRA',
          club_id: 4,
          goals: 0,
        },
        {
          player_name: 'Katiuscia',
          position: 'LATERAL',
          club_id: 4,
          goals: 0,
        },
        {
          player_name: 'Tamires',
          position: 'LATERAL',
          club_id: 4,
          goals: 0,
        },
        {
          player_name: 'Diany',
          position: 'MEIA',
          club_id: 4,
          goals: 1,
        },
        {
          player_name: 'Gabi Zanotti',
          position: 'MEIA',
          club_id: 4,
          goals: 1,
        },
        {
          player_name: 'Ingryd',
          position: 'MEIA',
          club_id: 4,
          goals: 0,
        },
        {
          player_name: 'Gabi Portilho',
          position: 'ATACANTE',
          club_id: 4,
          goals: 3,
        },
        {
          player_name: 'Miriã',
          position: 'ATACANTE',
          club_id: 4,
          goals: 1,
        },
        {
          player_name: 'Cacau',
          position: 'ATACANTE',
          club_id: 4,
          goals: 5,
        },
        {
          player_name: 'Taty SIlva',
          position: 'GOLEIRA',
          club_id: 5,
          goals: 0,
        },
        {
          player_name: 'Thalita',
          position: 'DEFENSOR',
          club_id: 5,
          goals: 0,
        },
        {
          player_name: 'Mariana Pires',
          position: 'DEFENSOR',
          club_id: 5,
          goals: 0,
        },
        {
          player_name: 'Eskerdinha',
          position: 'DEFENSOR',
          club_id: 5,
          goals: 0,
        },
        {
          player_name: 'Mayara Vaz',
          position: 'MEIA',
          club_id: 5,
          goals: 0,
        },
        {
          player_name: 'Duda',
          position: 'MEIA',
          club_id: 5,
          goals: 0,
        },
        {
          player_name: 'Lucero Robayo',
          position: 'MEIA',
          club_id: 5,
          goals: 1,
        },
        {
          player_name: 'Camila Ambrózio',
          position: 'MEIA',
          club_id: 5,
          goals: 1,
        },
        {
          player_name: 'Carol Shimo',
          position: 'MEIA',
          club_id: 5,
          goals: 0,
        },
        {
          player_name: 'Vanessa',
          position: 'ATACANTE',
          club_id: 5,
          goals: 3,
        },
        {
          player_name: 'Pâmela',
          position: 'ATACANTE',
          club_id: 5,
          goals: 3,
        },
        {
          player_name: 'Leilane',
          position: 'GOLEIRA',
          club_id: 6,
          goals: 0,
        },
        {
          player_name: 'Raquel Maisa',
          position: 'DEFENSOR',
          club_id: 6,
          goals: 1,
        },
        {
          player_name: 'Nicoly',
          position: 'DEFENSOR',
          club_id: 6,
          goals: 0,
        },
        {
          player_name: 'Ana Alice',
          position: 'DEFENSOR',
          club_id: 6,
          goals: 0,
        },
        {
          player_name: 'Catarina',
          position: 'MEIA',
          club_id: 6,
          goals: 1,
        },
        {
          player_name: 'Tamires',
          position: 'MEIA',
          club_id: 6,
          goals: 0,
        },
        {
          player_name: 'Aninha Hansen',
          position: 'MEIA',
          club_id: 6,
          goals: 0,
        },
        {
          player_name: 'Maísa',
          position: 'MEIA',
          club_id: 6,
          goals: 0,
        },
        {
          player_name: 'Laura Pigatin',
          position: 'ATACANTE',
          club_id: 6,
          goals: 0,
        },
        {
          player_name: 'Aline Milene',
          position: 'ATACANTE',
          club_id: 6,
          goals: 3,
        },
        {
          player_name: 'Sâmila Pryscila',
          position: 'ATACANTE',
          club_id: 6,
          goals: 2,
        },
        {
          player_name: 'Gabi Croco',
          position: 'GOLEIRA',
          club_id: 7,
          goals: 0,
        },
        {
          player_name: 'Cida',
          position: 'DEFENSOR',
          club_id: 7,
          goals: 0,
        },
        {
          player_name: 'Renata DIniz',
          position: 'DEFENSOR',
          club_id: 7,
          goals: 1,
        },
        {
          player_name: 'Débora Sorriso',
          position: 'LATERAL',
          club_id: 7,
          goals: 0,
        },
        {
          player_name: 'Raquel',
          position: 'LATERAL',
          club_id: 7,
          goals: 0,
        },
        {
          player_name: 'Bruna Rosa',
          position: 'MEIA',
          club_id: 7,
          goals: 0,
        },
        {
          player_name: 'Dedê',
          position: 'MEIA',
          club_id: 7,
          goals: 0,
        },
        {
          player_name: 'Jayanne',
          position: 'MEIA',
          club_id: 7,
          goals: 0,
        },
        {
          player_name: 'Andressa Lodi',
          position: 'ATACANTE',
          club_id: 7,
          goals: 0,
        },
        {
          player_name: 'Flávia',
          position: 'ATACANTE',
          club_id: 7,
          goals: 1,
        },
        {
          player_name: 'Rafa Barros',
          position: 'ATACANTE',
          club_id: 7,
          goals: 0,
        },
        {
          player_name: 'Lorena',
          position: 'GOLEIRA',
          club_id: 8,
          goals: 0,
        },
        {
          player_name: 'Sinara',
          position: 'LATERAL',
          club_id: 8,
          goals: 0,
        },
        {
          player_name: 'Vitória Kaíssa',
          position: 'LATERAL',
          club_id: 8,
          goals: 1,
        },
        {
          player_name: 'Andréia Rosa',
          position: 'DEFENSOR',
          club_id: 8,
          goals: 0,
        },
        {
          player_name: 'Lorena Gonzalez',
          position: 'DEFENSOR',
          club_id: 8,
          goals: 0,
        },
        {
          player_name: 'Kika Brandinho',
          position: 'MEIA',
          club_id: 8,
          goals: 1,
        },
        {
          player_name: 'Maglia',
          position: 'MEIA',
          club_id: 8,
          goals: 0,
        },
        {
          player_name: 'Mariza',
          position: 'MEIA',
          club_id: 8,
          goals: 1,
        },
        {
          player_name: 'Pri Back',
          position: 'MEIA',
          club_id: 8,
          goals: 0,
        },
        {
          player_name: 'Nathane Fabem',
          position: 'ATACANTE',
          club_id: 8,
          goals: 4,
        },
        {
          player_name: 'Eudimilla',
          position: 'ATACANTE',
          club_id: 8,
          goals: 2,
        },
        {
          player_name: 'Vivi',
          position: 'GOLEIRA',
          club_id: 9,
          goals: 0,
        },
        {
          player_name: 'Leidi',
          position: 'DEFENSOR',
          club_id: 9,
          goals: 0,
        },
        {
          player_name: 'Bruna Benites',
          position: 'DEFENSOR',
          club_id: 9,
          goals: 0,
        },
        {
          player_name: 'Ariane Cabrera',
          position: 'DEFENSOR',
          club_id: 9,
          goals: 0,
        },
        {
          player_name: 'Isa Haas',
          position: 'DEFENSOR',
          club_id: 9,
          goals: 0,
        },
        {
          player_name: 'Gilmara',
          position: 'MEIA',
          club_id: 9,
          goals: 0,
        },
        {
          player_name: 'Ju Ferreira',
          position: 'MEIA',
          club_id: 9,
          goals: 0,
        },
        {
          player_name: 'Rafa Travalão',
          position: 'MEIA',
          club_id: 9,
          goals: 1,
        },
        {
          player_name: 'Bárbara',
          position: 'MEIA',
          club_id: 9,
          goals: 1,
        },
        {
          player_name: 'Luana Gabias',
          position: 'ATACANTE',
          club_id: 9,
          goals: 2,
        },
        {
          player_name: 'Priscila',
          position: 'ATACANTE',
          club_id: 9,
          goals: 3,
        },
        {
          player_name: 'Janny',
          position: 'GOLEIRA',
          club_id: 10,
          goals: 0,
        },
        {
          player_name: 'Dih',
          position: 'DEFENSOR',
          club_id: 10,
          goals: 0,
        },
        {
          player_name: 'Luy',
          position: 'DEFENSOR',
          club_id: 10,
          goals: 0,
        },
        {
          player_name: 'Kati',
          position: 'LATERAL',
          club_id: 10,
          goals: 0,
        },
        {
          player_name: 'Madu',
          position: 'LATERAL',
          club_id: 10,
          goals: 0,
        },
        {
          player_name: 'Gabi Arcanjo',
          position: 'MEIA',
          club_id: 10,
          goals: 0,
        },
        {
          player_name: 'Isa',
          position: 'MEIA',
          club_id: 10,
          goals: 0,
        },
        {
          player_name: 'Monse',
          position: 'MEIA',
          club_id: 10,
          goals: 0,
        },
        {
          player_name: 'Farinon',
          position: 'ATACANTE',
          club_id: 10,
          goals: 0,
        },
        {
          player_name: 'Pelé',
          position: 'ATACANTE',
          club_id: 10,
          goals: 2,
        },
        {
          player_name: 'Robinha',
          position: 'ATACANTE',
          club_id: 10,
          goals: 2,
        },
        {
          player_name: 'Dalva',
          position: 'GOLEIRA',
          club_id: 11,
          goals: 0,
        },
        {
          player_name: 'Miriam',
          position: 'DEFENSOR',
          club_id: 11,
          goals: 0,
        },
        {
          player_name: 'Thaíni',
          position: 'DEFENSOR',
          club_id: 11,
          goals: 0,
        },
        {
          player_name: 'Júlia Cipriani',
          position: 'DEFENSOR',
          club_id: 11,
          goals: 0,
        },
        {
          player_name: 'Thays',
          position: 'DEFENSOR',
          club_id: 11,
          goals: 0,
        },
        {
          player_name: 'Yaki Vecca',
          position: 'DEFENSOR',
          club_id: 11,
          goals: 0,
        },
        {
          player_name: 'Luana Rodrigues',
          position: 'MEIA',
          club_id: 11,
          goals: 0,
        },
        {
          player_name: 'Juliana Santos',
          position: 'MEIA',
          club_id: 11,
          goals: 0,
        },
        {
          player_name: 'Jaine Lemke',
          position: 'MEIA',
          club_id: 11,
          goals: 0,
        },
        {
          player_name: 'Martinha',
          position: 'MEIA',
          club_id: 11,
          goals: 1,
        },
        {
          player_name: 'Aninha',
          position: 'ATACANTE',
          club_id: 11,
          goals: 2,
        },
        {
          player_name: 'Awanny',
          position: 'GOLEIRA',
          club_id: 12,
          goals: 0,
        },
        {
          player_name: 'Agustina',
          position: 'DEFENSOR',
          club_id: 12,
          goals: 1,
        },
        {
          player_name: 'Carolzinha',
          position: 'DEFENSOR',
          club_id: 12,
          goals: 0,
        },
        {
          player_name: 'Bruna Calderan',
          position: 'LATERAL',
          club_id: 12,
          goals: 2,
        },
        {
          player_name: 'Evelin',
          position: 'LATERAL',
          club_id: 12,
          goals: 1,
        },
        {
          player_name: 'Ana Clara',
          position: 'MEIA',
          club_id: 12,
          goals: 0,
        },
        {
          player_name: 'Ary Borges',
          position: 'MEIA',
          club_id: 12,
          goals: 0,
        },
        {
          player_name: 'Camilinha',
          position: 'MEIA',
          club_id: 12,
          goals: 0,
        },
        {
          player_name: 'Thayná',
          position: 'MEIA',
          club_id: 12,
          goals: 4,
        },
        {
          player_name: 'Carol Baiana',
          position: 'ATACANTE',
          club_id: 12,
          goals: 4,
        },
        {
          player_name: 'Mariana Alves',
          position: 'ATACANTE',
          club_id: 12,
          goals: 5,
        },
        {
          player_name: 'Thais Amorim',
          position: 'GOLEIRA',
          club_id: 13,
          goals: 0,
        },
        {
          player_name: 'Roberta Schroeder',
          position: 'DEFENSOR',
          club_id: 13,
          goals: 0,
        },
        {
          player_name: 'Lana',
          position: 'DEFENSOR',
          club_id: 13,
          goals: 0,
        },
        {
          player_name: 'Jamille',
          position: 'DEFENSOR',
          club_id: 13,
          goals: 0,
        },
        {
          player_name: 'Raquel',
          position: 'DEFENSOR',
          club_id: 13,
          goals: 0,
        },
        {
          player_name: 'Letícia Leme',
          position: 'MEIO',
          club_id: 13,
          goals: 0,
        },
        {
          player_name: 'Taci Sam',
          position: 'MEIO',
          club_id: 13,
          goals: 0,
        },
        {
          player_name: 'Eliane',
          position: 'MEIO',
          club_id: 13,
          goals: 0,
        },
        {
          player_name: 'Amanda Ribeiro',
          position: 'MEIO',
          club_id: 13,
          goals: 1,
        },
        {
          player_name: 'Tábatha',
          position: 'ATACANTE',
          club_id: 13,
          goals: 1,
        },
        {
          player_name: 'Daniele',
          position: 'ATACANTE',
          club_id: 13,
          goals: 3,
        },
        {
          player_name: 'Camila Gomes',
          position: 'GOLEIRA',
          club_id: 14,
          goals: 0,
        },
        {
          player_name: 'Sassá',
          position: 'DEFENSOR',
          club_id: 14,
          goals: 1,
        },
        {
          player_name: 'Tayla',
          position: 'DEFENSOR',
          club_id: 14,
          goals: 0,
        },
        {
          player_name: 'Camila',
          position: 'DEFENSOR',
          club_id: 14,
          goals: 0,
        },
        {
          player_name: 'Bruninha',
          position: 'LATERAL',
          club_id: 14,
          goals: 1,
        },
        {
          player_name: 'Fe Palermo',
          position: 'LATERAL',
          club_id: 14,
          goals: 1,
        },
        {
          player_name: 'Júlia Daltoé',
          position: 'MEIA',
          club_id: 14,
          goals: 0,
        },
        {
          player_name: 'Gi Fernandes',
          position: 'MEIA',
          club_id: 14,
          goals: 0,
        },
        {
          player_name: 'Rita Bove',
          position: 'MEIA',
          club_id: 14,
          goals: 2,
        },
        {
          player_name: 'Cristiane',
          position: 'ATACANTE',
          club_id: 14,
          goals: 5,
        },
        {
          player_name: 'Amanda Gutierrez',
          position: 'ATACANTE',
          club_id: 14,
          goals: 3,
        },
        {
          player_name: 'Zani',
          position: 'GOLEIRA',
          club_id: 15,
          goals: 0,
        },
        {
          player_name: 'Gabi Batista',
          position: 'DEFENSOR',
          club_id: 15,
          goals: 0,
        },
        {
          player_name: 'Verónica Riveros',
          position: 'DEFENSOR',
          club_id: 15,
          goals: 0,
        },
        {
          player_name: 'Karen',
          position: 'DEFENSOR',
          club_id: 15,
          goals: 0,
        },
        {
          player_name: 'Vitória Calhau',
          position: 'DEFENSOR',
          club_id: 15,
          goals: 0,
        },
        {
          player_name: 'Larissa Vasconcelos',
          position: 'MEIA',
          club_id: 15,
          goals: 0,
        },
        {
          player_name: 'Mariane',
          position: 'MEIA',
          club_id: 15,
          goals: 1,
        },
        {
          player_name: 'Adyla',
          position: 'MEIA',
          club_id: 15,
          goals: 0,
        },
        {
          player_name: 'Rafa Marques',
          position: 'MEIA',
          club_id: 15,
          goals: 0,
        },
        {
          player_name: 'Thainá',
          position: 'ATACANTE',
          club_id: 15,
          goals: 1,
        },
        {
          player_name: 'Giovânia',
          position: 'ATACANTE',
          club_id: 15,
          goals: 3,
        },
        {
          player_name: 'Thaís Helena',
          position: 'GOLEIRA',
          club_id: 16,
          goals: 0,
        },
        {
          player_name: 'Letícia Alves',
          position: 'DEFENSOR',
          club_id: 16,
          goals: 0,
        },
        {
          player_name: 'Natane',
          position: 'DEFENSOR',
          club_id: 16,
          goals: 0,
        },
        {
          player_name: 'Dani Silva',
          position: 'DEFENSOR',
          club_id: 16,
          goals: 1,
        },
        {
          player_name: 'Gislaine',
          position: 'DEFENSOR',
          club_id: 16,
          goals: 0,
        },
        {
          player_name: 'Nath Pitbull',
          position: 'MEIA',
          club_id: 16,
          goals: 0,
        },
        {
          player_name: 'Formiga',
          position: 'MEIA',
          club_id: 16,
          goals: 2,
        },
        {
          player_name: 'Duda',
          position: 'MEIA',
          club_id: 16,
          goals: 0,
        },
        {
          player_name: 'Naná',
          position: 'MEIA',
          club_id: 16,
          goals: 2,
        },
        {
          player_name: 'Mônica Bitencourt',
          position: 'ATACANTE',
          club_id: 16,
          goals: 1,
        },
        {
          player_name: 'Giovaninha',
          position: 'ATACANTE',
          club_id: 16,
          goals: 3,
        },
      ],
      {},
    );
  },

  down: async (queryInterface) => {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     */
    await queryInterface.bulkDelete('players', null, {});
  },
};
